### ISSUE TITLE
New community-managed packages: ArchLinux: AUR

### ISSUE THREAD

**Issue by kseistrup** [riquito/tuc#55]
FYI: `tuc` is available as two separate packages on AUR:

1. https://aur.archlinux.org/packages/tuc (will be compiled at time of installation)
2. https://aur.archlinux.org/packages/tuc-bin (pre-compiled binaries)

They can be installed with:

1. `yay -S tuc`
2. `yay -S tuc-bin`

The latter will install both `tuc` and `tuc-regex` from the binary release here on Microsoft Github.

**Comment by alebcay** [comment]
Hello there 👋 Homebrew maintainer here to mention that [`tuc` is now available in Homebrew as well for installation on macOS and Linux](https://formulae.brew.sh/formula/tuc).

I would also consider just replacing the "Community-Managed Packages" section of the documentation with [a dynamic badge from Repology](https://repology.org/project/tuc-cut/badges), which should automatically update to reflect which repositories/package managers may be carrying `tuc`.

For instance, `[![Packaging status](https://repology.org/badge/vertical-allrepos/tuc-cut.svg)](https://repology.org/project/tuc-cut/versions)` looks like:

[![Packaging status](https://repology.org/badge/vertical-allrepos/tuc-cut.svg)](https://repology.org/project/tuc-cut/versions)

**Comment by riquito** [comment]
Thank you @kseistrup and @alebcay, I would never be able to maintain multiple platforms by myself, you're amazing!

I updated the README with the automatic table and dedicated doc in this PR https://github.com/riquito/tuc/pull/56
