### ISSUE TITLE
Help needed: how to split on multiple delimiters in one run?

### ISSUE THREAD

**Issue by kseistrup** [riquito/tuc#88]
I wanted to split on `[ \t]` (like Python's `.split()` does if no delimiter is given), and I guess it can be done with e.g.:

```sh
  tuc -p -r ' '
```

But more generally: What if the delimiters were not SPACE and TAB, but say any of `x`, `y` or `z`?

```sh
$ echo '1x2y3z4' | tuc -d '[xyz]' -f 2
1x2y3z4
$ echo '1x2y3z4' | tuc -d '(x|y|z)' -f 2
1x2y3z4
```

Have I misunderstood how the regex thing is supposed to work? Line 371 in `cut_str.rs` reads:

```rs
            normal: Regex::from_str("[.,]").unwrap(),
```

https://github.com/riquito/tuc/blob/master/src/cut_str.rs#L371

This suggests that `-d [xyz]` should be alright, doesn't it?

Will it be overkill with a cookbook wiki with recipes here?

**Comment by riquito** [comment]
> Have I misunderstood how the regex thing is supposed to work? 

You were almost there, you are using `-d`, which splits on fixed strings, instead of  `-e`, which splits on regex. 

```sh
# split using regex
echo '1x2y3z4' | tuc -e '[xyz]' -f 2
2
```

Using `-d` you'd need to have the same identical string in the input

```sh
# split using fixed string
echo '1[xyz]2' | tuc -d '[xyz]' -f 2
2
```

Pretty sure you got bit by the documentation bug you mentioned in https://github.com/riquito/tuc/issues/87

> Will it be overkill with a cookbook wiki with recipes here?

It's a bit overkill for now. There's an example exactly about this in the README, perhaps you missed it? 

```sh
# Cut using regular expressions
❯ echo "a,b, c" | tuc -e '[, ]+' -f 1,3
ac
```

**Comment by kseistrup** [comment]
> Pretty sure you got bit by the documentation bug you mentioned in #87

Thanks for your help, it all makes sense now. Yes, I was hit by #87, combined with the release note saying that the “regex feature is enabled by default“, which I took to mean that “`-e` is unnecessary now, `-d` will automatically detect if we have a regex”. I feel a little stupid now. :zany_face:
