### ISSUE TITLE
Was `v1.0.0` retagged?

### ISSUE THREAD

**Issue by ZhongRuoyu** [riquito/tuc#91]
Hi! Homebrew maintainer here. We noticed that tuc `v1.0.0` was re-tagged and would like to confirm if that's intended (and is not a consequence of the repo being compromised somehow). As mentioned in [Git's documentation](https://git-scm.com/docs/git-tag#_on_re_tagging), re-tagging is an "insane thing" to do.

**Comment by riquito** [comment]
Sorry to reply this late, I somehow missed this notification. Looking at the history it appears I indeed retagged it, which I agree was a mistake, I was not in my right mind. I have double checked the commits and they were not tampered with

**Comment by ZhongRuoyu** [comment]
Thanks for confirming that, @riquito. :)
